# Generated by Django 4.0.4 on 2023-11-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, db_column='mensaje_texto'),
        ),
    ]
