# Generated by Django 4.0.4 on 2023-10-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '__first__'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(db_column='persona_rol', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='roles.role'),
        ),
    ]
