# Generated by Django 4.0.4 on 2023-11-01 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='daily_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='last_message_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
