# Generated by Django 4.0.4 on 2022-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='rol_nombre', max_length=50)),
                ('description', models.CharField(blank=True, db_column='rol_descripcion', max_length=500, null=True)),
                ('level_of_access', models.IntegerField(blank=True, db_column='rol_nivel_acceso', null=True, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
