# Generated by Django 4.0.4 on 2023-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AlterField(
            model_name='role',
            name='level_of_access',
            field=models.IntegerField(blank=True, db_column='rol_nivel_acceso', null=True),
        ),
    ]
